server:
  port : 8081

spring.application.name: client

management:
  endpoints.web.exposure.include: '*' # health,info,prometheus

  tracing:
    enabled: true

logging:
  level:
    web: trace
  pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  codec:
    log-request-details: true
