spring.application.name: client

management:
  endpoints.web.exposure.include: '*' # health,info,prometheus

  tracing:
    enabled: true

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
