server:
  port: 8082

spring.application.name: server

management:
  endpoints.web.exposure.include: '*' # health,info,prometheus

  tracing:
    sampling:
      probability: 1.0
    enabled: true

logging:
  level:
    web: trace
  pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


spring:
  codec:
    log-request-details: true
